//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockus_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blockus_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Board style.
        /// </summary>
        public static string Configuration_boardStyle {
            get {
                return ResourceManager.GetString("Configuration_boardStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Losses.
        /// </summary>
        public static string Configuration_loses {
            get {
                return ResourceManager.GetString("Configuration_loses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change your password.
        /// </summary>
        public static string Configuration_modifyPassword {
            get {
                return ResourceManager.GetString("Configuration_modifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Configuration_settings {
            get {
                return ResourceManager.GetString("Configuration_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string Configuration_stats {
            get {
                return ResourceManager.GetString("Configuration_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiles style: .
        /// </summary>
        public static string Configuration_tilesStyle {
            get {
                return ResourceManager.GetString("Configuration_tilesStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victories.
        /// </summary>
        public static string Configuration_victories {
            get {
                return ResourceManager.GetString("Configuration_victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are already logged in.
        /// </summary>
        public static string Error_alreadyLogged {
            get {
                return ResourceManager.GetString("Error_alreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incomplete fields. Fill in all fields and try again..
        /// </summary>
        public static string Error_incompleteFields {
            get {
                return ResourceManager.GetString("Error_incompleteFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The entered data does not match.
        /// </summary>
        public static string Error_noCoincidences {
            get {
                return ResourceManager.GetString("Error_noCoincidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred while trying to connect to the database, please try it later..
        /// </summary>
        public static string Error_noConnection {
            get {
                return ResourceManager.GetString("Error_noConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred while trying to retrieve your data..
        /// </summary>
        public static string Error_retrievingData {
            get {
                return ResourceManager.GetString("Error_retrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new password cannot be the same as your current password..
        /// </summary>
        public static string Error_samePassword {
            get {
                return ResourceManager.GetString("Error_samePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred while trying to connect to the server, try again later..
        /// </summary>
        public static string Error_serverConnection {
            get {
                return ResourceManager.GetString("Error_serverConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password must only have letters and/or numbers..
        /// </summary>
        public static string Error_specialCharacters {
            get {
                return ResourceManager.GetString("Error_specialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred while updating your data, please try again later..
        /// </summary>
        public static string Error_unsuccesfulOperation {
            get {
                return ResourceManager.GetString("Error_unsuccesfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong credentials.
        /// </summary>
        public static string Error_wrongCredentials {
            get {
                return ResourceManager.GetString("Error_wrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete friend.
        /// </summary>
        public static string FriendCard_delete {
            get {
                return ResourceManager.GetString("FriendCard_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My friends.
        /// </summary>
        public static string Friends_addedFriends {
            get {
                return ResourceManager.GetString("Friends_addedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Friends_search {
            get {
                return ResourceManager.GetString("Friends_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search by username.
        /// </summary>
        public static string Friends_searchUser {
            get {
                return ResourceManager.GetString("Friends_searchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Global_cancelButton {
            get {
                return ResourceManager.GetString("Global_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string Global_continueButton {
            get {
                return ResourceManager.GetString("Global_continueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blockus.
        /// </summary>
        public static string Global_gameName {
            get {
                return ResourceManager.GetString("Global_gameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string Global_language {
            get {
                return ResourceManager.GetString("Global_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create an account.
        /// </summary>
        public static string Global_noAccount {
            get {
                return ResourceManager.GetString("Global_noAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string Global_okButton {
            get {
                return ResourceManager.GetString("Global_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Global_password {
            get {
                return ResourceManager.GetString("Global_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the match code shared by the host to be able to play with your friends..
        /// </summary>
        public static string Global_privateMode {
            get {
                return ResourceManager.GetString("Global_privateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game will search for a match you can join..
        /// </summary>
        public static string Global_publicMode {
            get {
                return ResourceManager.GetString("Global_publicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return.
        /// </summary>
        public static string Global_return {
            get {
                return ResourceManager.GetString("Global_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Global_username {
            get {
                return ResourceManager.GetString("Global_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code to join a match.
        /// </summary>
        public static string JoinMatch_enterCode {
            get {
                return ResourceManager.GetString("JoinMatch_enterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match you tried to join is already full..
        /// </summary>
        public static string JoinMatch_fullMatch {
            get {
                return ResourceManager.GetString("JoinMatch_fullMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The host has left the match, you will be sent back to the lobby..
        /// </summary>
        public static string JoinMatch_hostLeft {
            get {
                return ResourceManager.GetString("JoinMatch_hostLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string JoinMatch_join {
            get {
                return ResourceManager.GetString("JoinMatch_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No match found for the entered code..
        /// </summary>
        public static string JoinMatch_noMatches {
            get {
                return ResourceManager.GetString("JoinMatch_noMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred while trying to join the match.
        /// </summary>
        public static string JoinMatch_unableToJoin {
            get {
                return ResourceManager.GetString("JoinMatch_unableToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string Lobby_configuration {
            get {
                return ResourceManager.GetString("Lobby_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CreateMatch.
        /// </summary>
        public static string Lobby_createMatch {
            get {
                return ResourceManager.GetString("Lobby_createMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Lobby_friends {
            get {
                return ResourceManager.GetString("Lobby_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        public static string Lobby_joinMatch {
            get {
                return ResourceManager.GetString("Lobby_joinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Lobby_logout {
            get {
                return ResourceManager.GetString("Lobby_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string Login_forgotPassword {
            get {
                return ResourceManager.GetString("Login_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest.
        /// </summary>
        public static string Login_guest {
            get {
                return ResourceManager.GetString("Login_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your account.
        /// </summary>
        public static string Login_in {
            get {
                return ResourceManager.GetString("Login_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string Login_log {
            get {
                return ResourceManager.GetString("Login_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login_login {
            get {
                return ResourceManager.GetString("Login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an account? Register here.
        /// </summary>
        public static string Login_noAccount {
            get {
                return ResourceManager.GetString("Login_noAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred: creating match.
        /// </summary>
        public static string MatchDetails_createError {
            get {
                return ResourceManager.GetString("MatchDetails_createError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred: leaving match .
        /// </summary>
        public static string MatchDetails_errorLeft {
            get {
                return ResourceManager.GetString("MatchDetails_errorLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game mode: .
        /// </summary>
        public static string MatchDetails_gameMode {
            get {
                return ResourceManager.GetString("MatchDetails_gameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match code:.
        /// </summary>
        public static string MatchDetails_matchCode {
            get {
                return ResourceManager.GetString("MatchDetails_matchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of players.
        /// </summary>
        public static string MatchDetails_noPlayers {
            get {
                return ResourceManager.GetString("MatchDetails_noPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only players with the match code can join..
        /// </summary>
        public static string MatchDetails_note {
            get {
                return ResourceManager.GetString("MatchDetails_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        public static string MatchDetails_private {
            get {
                return ResourceManager.GetString("MatchDetails_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string MatchDetails_public {
            get {
                return ResourceManager.GetString("MatchDetails_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching for players.
        /// </summary>
        public static string MatchDetails_searchingPlayers {
            get {
                return ResourceManager.GetString("MatchDetails_searchingPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for a player.
        /// </summary>
        public static string MatchDetails_waitingPlayer {
            get {
                return ResourceManager.GetString("MatchDetails_waitingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password:.
        /// </summary>
        public static string ModifyPassword_actualPassword {
            get {
                return ResourceManager.GetString("ModifyPassword_actualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change your password.
        /// </summary>
        public static string ModifyPassword_modify {
            get {
                return ResourceManager.GetString("ModifyPassword_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your new password: .
        /// </summary>
        public static string ModifyPassword_newPassword {
            get {
                return ResourceManager.GetString("ModifyPassword_newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOTE: once your password is modified you will be asked to log in again with your new password..
        /// </summary>
        public static string ModifyPassword_note {
            get {
                return ResourceManager.GetString("ModifyPassword_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been modified succesfully .
        /// </summary>
        public static string ModifyPassword_passwordModified {
            get {
                return ResourceManager.GetString("ModifyPassword_passwordModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for a player.
        /// </summary>
        public static string PlayerCard {
            get {
                return ResourceManager.GetString("PlayerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your password.
        /// </summary>
        public static string Register_confirmPassword {
            get {
                return ResourceManager.GetString("Register_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred while creating your account.
        /// </summary>
        public static string Register_creationFailure {
            get {
                return ResourceManager.GetString("Register_creationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register success.
        /// </summary>
        public static string Register_creationSuccess {
            get {
                return ResourceManager.GetString("Register_creationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Register_email {
            get {
                return ResourceManager.GetString("Register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email must be &apos;@gmail.com&apos;.
        /// </summary>
        public static string Register_emailRestriction {
            get {
                return ResourceManager.GetString("Register_emailRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid data.
        /// </summary>
        public static string Register_incorrectData {
            get {
                return ResourceManager.GetString("Register_incorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note: once you click on &apos;Continue&apos; an email will be sent to the email address above, with a verification code for the correct creation of your account..
        /// </summary>
        public static string Register_signUpNote {
            get {
                return ResourceManager.GetString("Register_signUpNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been succesfully created!.
        /// </summary>
        public static string Register_success {
            get {
                return ResourceManager.GetString("Register_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string UserCard {
            get {
                return ResourceManager.GetString("UserCard", resourceCulture);
            }
        }
    }
}
