//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockus_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blockus_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Board style.
        /// </summary>
        internal static string Configuration_boardStyle {
            get {
                return ResourceManager.GetString("Configuration_boardStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Losses.
        /// </summary>
        internal static string Configuration_loses {
            get {
                return ResourceManager.GetString("Configuration_loses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change your password.
        /// </summary>
        internal static string Configuration_modifyPassword {
            get {
                return ResourceManager.GetString("Configuration_modifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Configuration_Settings {
            get {
                return ResourceManager.GetString("Configuration_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        internal static string Configuration_stats {
            get {
                return ResourceManager.GetString("Configuration_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiles style: .
        /// </summary>
        internal static string Configuration_TilesStyle {
            get {
                return ResourceManager.GetString("Configuration_TilesStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victories.
        /// </summary>
        internal static string Configuration_victories {
            get {
                return ResourceManager.GetString("Configuration_victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My friends.
        /// </summary>
        internal static string Friends_addedFriends {
            get {
                return ResourceManager.GetString("Friends_addedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search by username.
        /// </summary>
        internal static string Friends_searchUser {
            get {
                return ResourceManager.GetString("Friends_searchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string Global_back {
            get {
                return ResourceManager.GetString("Global_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Global_cancelButton {
            get {
                return ResourceManager.GetString("Global_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string Global_continueButton {
            get {
                return ResourceManager.GetString("Global_continueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create an account.
        /// </summary>
        internal static string Global_noAccount {
            get {
                return ResourceManager.GetString("Global_noAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string Global_okButton {
            get {
                return ResourceManager.GetString("Global_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the match code shared by the host to be able to play with your friends..
        /// </summary>
        internal static string Global_privateMode {
            get {
                return ResourceManager.GetString("Global_privateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game will search for a match you can join..
        /// </summary>
        internal static string Global_publicMode {
            get {
                return ResourceManager.GetString("Global_publicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the match code to join a match.
        /// </summary>
        internal static string JoinMatch_enterCode {
            get {
                return ResourceManager.GetString("JoinMatch_enterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        internal static string JoinMatch_join {
            get {
                return ResourceManager.GetString("JoinMatch_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        internal static string Lobby_Configuration {
            get {
                return ResourceManager.GetString("Lobby_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match.
        /// </summary>
        internal static string Lobby_createMatch {
            get {
                return ResourceManager.GetString("Lobby_createMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        internal static string Lobby_Friends {
            get {
                return ResourceManager.GetString("Lobby_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        internal static string Lobby_joinMatch {
            get {
                return ResourceManager.GetString("Lobby_joinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        internal static string Lobby_logout {
            get {
                return ResourceManager.GetString("Lobby_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        internal static string Login_forgotPassword {
            get {
                return ResourceManager.GetString("Login_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as guest .
        /// </summary>
        internal static string Login_guest {
            get {
                return ResourceManager.GetString("Login_guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login_login {
            get {
                return ResourceManager.GetString("Login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an account? Register here.
        /// </summary>
        internal static string Login_noAccount {
            get {
                return ResourceManager.GetString("Login_noAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game mode:.
        /// </summary>
        internal static string MatchDetails_gameMode {
            get {
                return ResourceManager.GetString("MatchDetails_gameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match code: .
        /// </summary>
        internal static string MatchDetails_matchCode {
            get {
                return ResourceManager.GetString("MatchDetails_matchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of players: .
        /// </summary>
        internal static string MatchDetails_noPlayers {
            get {
                return ResourceManager.GetString("MatchDetails_noPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only players with the match code can join..
        /// </summary>
        internal static string MatchDetails_note {
            get {
                return ResourceManager.GetString("MatchDetails_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private.
        /// </summary>
        internal static string MatchDetails_private {
            get {
                return ResourceManager.GetString("MatchDetails_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        internal static string MatchDetails_public {
            get {
                return ResourceManager.GetString("MatchDetails_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching for players.
        /// </summary>
        internal static string MatchDetails_searchingPlayers {
            get {
                return ResourceManager.GetString("MatchDetails_searchingPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for a player.
        /// </summary>
        internal static string MatchDetails_waitingPlayer {
            get {
                return ResourceManager.GetString("MatchDetails_waitingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password: .
        /// </summary>
        internal static string ModifyPassword_actualPassword {
            get {
                return ResourceManager.GetString("ModifyPassword_actualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change your password.
        /// </summary>
        internal static string ModifyPassword_modify {
            get {
                return ResourceManager.GetString("ModifyPassword_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your new password: .
        /// </summary>
        internal static string ModifyPassword_newPassword {
            get {
                return ResourceManager.GetString("ModifyPassword_newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOTE: once your password is modified you will be asked to log in again with your new password..
        /// </summary>
        internal static string ModifyPassword_note {
            get {
                return ResourceManager.GetString("ModifyPassword_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your password.
        /// </summary>
        internal static string Register_confirmPassword {
            get {
                return ResourceManager.GetString("Register_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Register_email {
            get {
                return ResourceManager.GetString("Register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email must be &apos;@gmail.com&apos;.
        /// </summary>
        internal static string Register_emailRestriction {
            get {
                return ResourceManager.GetString("Register_emailRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note: once you click on &apos;Continue&apos; an email will be sent to the email address above, with a verification code for the correct creation of your account..
        /// </summary>
        internal static string Register_signUpNote {
            get {
                return ResourceManager.GetString("Register_signUpNote", resourceCulture);
            }
        }
    }
}
